USE [master]
GO
/****** Object:  Database [MegaCitycab]    Script Date: 3/14/2025 12:10:10 AM ******/
CREATE DATABASE [MegaCitycab]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MegaCitycab', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\MegaCitycab.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MegaCitycab_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\MegaCitycab_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [MegaCitycab] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MegaCitycab].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MegaCitycab] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MegaCitycab] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MegaCitycab] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MegaCitycab] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MegaCitycab] SET ARITHABORT OFF 
GO
ALTER DATABASE [MegaCitycab] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MegaCitycab] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MegaCitycab] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MegaCitycab] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MegaCitycab] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MegaCitycab] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MegaCitycab] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MegaCitycab] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MegaCitycab] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MegaCitycab] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MegaCitycab] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MegaCitycab] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MegaCitycab] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MegaCitycab] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MegaCitycab] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MegaCitycab] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MegaCitycab] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MegaCitycab] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MegaCitycab] SET  MULTI_USER 
GO
ALTER DATABASE [MegaCitycab] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MegaCitycab] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MegaCitycab] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MegaCitycab] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MegaCitycab] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MegaCitycab] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [MegaCitycab] SET QUERY_STORE = ON
GO
ALTER DATABASE [MegaCitycab] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [MegaCitycab]
GO
/****** Object:  Table [dbo].[admin]    Script Date: 3/14/2025 12:10:11 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[admin](
	[admin_id] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](50) NOT NULL,
	[email] [varchar](100) NOT NULL,
	[phone] [varchar](15) NOT NULL,
	[nic] [varchar](20) NOT NULL,
	[password] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[admin_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[nic] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[bookings]    Script Date: 3/14/2025 12:10:11 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[bookings](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[pickup] [nvarchar](255) NULL,
	[dropoff] [nvarchar](255) NULL,
	[vehicleType] [nvarchar](50) NULL,
	[distance] [float] NULL,
	[price] [float] NULL,
	[bookingDate] [datetime] NULL,
	[customerName] [nvarchar](255) NULL,
	[email] [nvarchar](255) NULL,
	[phone] [nvarchar](50) NULL,
	[specialRequests] [nvarchar](max) NULL,
	[status] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[customer]    Script Date: 3/14/2025 12:10:11 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[customer](
	[customer_id] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](50) NOT NULL,
	[email] [varchar](100) NOT NULL,
	[password] [varchar](255) NOT NULL,
	[phone] [varchar](20) NOT NULL,
	[address] [text] NOT NULL,
	[nic] [varchar](20) NOT NULL,
	[created_at] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[customer_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[nic] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[dri]    Script Date: 3/14/2025 12:10:11 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[dri](
	[driver_id] [int] IDENTITY(1,1) NOT NULL,
	[first_name] [varchar](50) NOT NULL,
	[last_name] [varchar](50) NOT NULL,
	[email] [varchar](100) NOT NULL,
	[password] [varchar](255) NOT NULL,
	[phone] [varchar](20) NOT NULL,
	[vehicle_types] [varchar](100) NOT NULL,
	[vehicle_no] [varchar](50) NOT NULL,
	[status] [varchar](20) NOT NULL,
	[profile_picture] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[driver_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[vehicle_no] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[drivers]    Script Date: 3/14/2025 12:10:11 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[drivers](
	[driver_id] [int] NOT NULL,
	[first_name] [varchar](255) NULL,
	[last_name] [varchar](255) NULL,
	[email] [varchar](255) NULL,
	[phone] [varchar](255) NULL,
	[vehicle_type] [varchar](255) NULL,
	[vehicle_no] [varchar](255) NULL,
	[status] [varchar](50) NULL,
	[profile_picture] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[driver_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[bookings] ADD  DEFAULT ('pending') FOR [status]
GO
ALTER TABLE [dbo].[customer] ADD  DEFAULT (getdate()) FOR [created_at]
GO
ALTER TABLE [dbo].[dri]  WITH CHECK ADD CHECK  (([status]='Inactive' OR [status]='Active'))
GO
USE [master]
GO
ALTER DATABASE [MegaCitycab] SET  READ_WRITE 
GO
